### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by psychemedia** [jameslmartin/jupyter-a11y#1]
Hi

A couple of typos in README:

`reader_js = 'https://raw.githubusercontent.com/jameslmartin/jupyter-a11y/master/reader.js'`
should be:
`reader_js = 'https://raw.githubusercontent.com/jameslmartin/jupyter-a11y/master/nbreader.js'`

`Jupyter.utils.load_extensions('reader')`
should be:
`Jupyter.utils.load_extensions('nbreader')`

PS Love this extension - will be exploring its use in an educational context.

**Comment by jameslmartin** [comment]
This should have been fixed by a98f32c
