### ISSUE TITLE
Packaging jupyter-a11y / nbreader as a self-installing notebook extension

### ISSUE THREAD

**Issue by psychemedia** [jameslmartin/jupyter-a11y#5]
As part of an project updating some educational materials delivered via Jupyter notebooks, I intend to start looking again at how we can better support students with a range of accessibility issues, as well as improving the accessible design of the materials in general to better support all users.

The event driven approach of the `juptyer-a11y`/`nbreader` extension is really interesting, I think. To try to make it a bit easy to work with and explore / extend, I've made a start on packaging it as a self-installing notebook extension: https://github.com/ouseful-backup/jupyter-a11y

By the by, as per  https://github.com/jameslmartin/jupyter-a11y/issues/3, and not withstanding your reply to it, it would be really useful if there was an official permissive license posted for your code. Institutional policies are such that if anyone checked, I could well be prevented internally from releasing anything to students that is clearly derived from this repo on grounds that the rights position is unclear.

**Comment by jameslmartin** [comment]
@psychemedia hey there! Glad you found me. I'm out of the loop on the current state of extension/package management for Jupyter, so I'm curious to hear what may be a best practice.

From an institutional standpoint, what is the easiest permissive license to deal with? I assume the MIT license may be a good fit. Would the GNU license be prohibitive to your work?

**Comment by psychemedia** [comment]
@jameslmartin Thanks for getting back to me; I generally go with MIT, but if you preferred to license it in accord w/ other Jupyter repos that'd be fine too; I suspect no-one really looks too hard, TBH, but I'm just trying to pre-empt blockers!

Re: packaging best practice - don't look to me then! I simply borrowed from another extension that word some time down the line (last few months) and have been cribbing myself ever since;-)

**Comment by jameslmartin** [comment]
Official license added, thanks for bringing this up. Hope the extension serves as a good launching point and helps in some way!
